version: "3.9"
name: "kalebe"

services:
  backend:
    image: kalebenascimento/backend:latest
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:Aula*infra@aws-db.c5qqqwoou4u8.us-east-1.rds.amazonaws.com:5432/aws-db"
      NODE_ENV: development
    ports:
      - "3030:3030"
    networks:
      - app_network
    command: npm start

  frontend:
    image: kalebenascimento/frontend:latest
    container_name: frontend
    restart: always
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network
    command: npm start

networks:
  app_network:
    driver: bridge

