version: "3.9"
name: "kalebe"

services:
  database:
    image: postgres
    container_name: testePostgre
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    image: kalebenascimento/backend:latest
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: "postgresql://admin:admin@database:5432/database"
      NODE_ENV: development
    ports:
      - "3030:3030"
    depends_on:
      - database
    networks:
      - app_network
    command: npm start

  frontend:
    image: kalebenascimento/frontend:latest
    container_name: frontend
    restart: always
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network
    command: npm start

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
    driver: local