version: "3.9"
name: "kalebe"

services:

  # database:
  #   image: postgres
  #   container_name: testePostgre
  #   restart: always
  #   ports:
  #     - "5433:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: Aula*infra
  #     POSTGRES_DB: aws-db
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - app_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:postgres123@aws-db-novo.c5qqqwoou4u8.us-east-1.rds.amazonaws.com:5432/aws_db_novo"
      NODE_ENV: development
    ports:
      - "3030:3030"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_network
    depends_on:
      - database
    command: npm start


  frontend:
    image: kalebenascimento/frontend:latest
    container_name: frontend
    restart: always
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network
    command: npm start

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
    driver: local